### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by Littie** [paschaldev/laravauth#1]
Hi. I found several errors. First at all for me in laravel v5.4.33 routing doesn't work. After logining i catch 

> "Route [laravauth_email_response] not defined"

if i change route defining in service provider on `$this->loadRoutesFrom(__DIR__.'/../routes/web.php');` routes are work

Second. In EmailToken and TwoFactorSms classes in login method you create redirect with 'laravauth_var' session var but in LaravauthLoginController in emailResponse and smsResponse methods you check 'Laravauth_var' with first uppercase letter. It doesn't work for me and i catch 404 error

Third. In LaravauthLoginController in emailResponse and smsResponse methods you return view

> Laravauth::email_response
> Laravauth::sms_response

but in service provider, view is defined as 'laravauth' - with first lowercase letter. It doesn't work for me.

**Comment by paschaldev** [comment]
Thanks for the info @Littie, will check this and update very soon.

**Comment by paschaldev** [comment]
This has been resolved in version 1.0.2.

Thanks for notice, all bugs have been fixed and this issue will now be closed.

**Comment by sdkcodes** [comment]
Hi, this issue doesn't appear to be fixed
Route [laravauth_email_response] not defined.

**Comment by paschaldev** [comment]
@sdkcodes What version of Laravel are you running?

**Comment by sdkcodes** [comment]
Laravel 5.4
I already created a workaround though
I created a named route `laravauth_email_reponse` and returned the proper view. And it works
Another questions though, can the package be used such that it sends the code to email (instead of the link) ?

**Comment by paschaldev** [comment]
@sdkcodes No for now but I'll consider that in the next update.

By the way, the package has a named route for that already. I just reinstalled and tried, everythng worked. 

Try and remove the named route you manually added and run `php artisan route:list` in your laravel directory and paste the output here.

This was the named route in mine:

GET|HEAD      | login/email            | **laravauth_email_response** | PaschalDev\Laravauth\Http\Controllers\LaravauthLoginController@emailResponse | web,guest
